# Generated by Django 5.0.3 on 2024-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='played_before',
            field=models.BooleanField(default=False),
        ),
    ]
